### ISSUE TITLE
Netbeans 10 Support

### ISSUE THREAD

**Issue by AndreasIgelCC** [hlavki/netbeans-svuid-generator#1]
I realy like your plugin, it makes handling serializable interface much easier. Please support Netbeans 10. Thank you!

**Comment by hlavki** [comment]
you can download version for netbeans 10 here: http://plugins.netbeans.org/plugin/6887/?show=true#v9969

**Comment by AndreasIgelCC** [comment]
Unfortunately not solved. When plugin is installed, i get an warning tone when trying to open serializable actions menu. Not even the default actions appear when selecting the yellow action item.

**Comment by hlavki** [comment]
I tested it and it works. Try to restart IDE.

**Comment by AndreasIgelCC** [comment]
Sorry, you are right. The error came from another plugin which has been activated on the same moment like the SVUID-Generator. Seems like netbeans manages all manuell installed plugins in one bundle.

Thank you for your quick responses!

**Comment by hlavki** [comment]
@AndreasIgelCC no problem, glad it works!
